[package]
name = "lenv"
version = "0.1.0"
edition = "2021"
authors = ["Alice Chen <alice.chen.500@gmail.com>"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "3.1.8", features = ["derive"] }
gtmpl = "0.7"